### ISSUE TITLE
Video_collection Binary file

### ISSUE THREAD

**Issue by DooDip** [nyavramov/fast_scene_segmentation#2]
I was unable to install the script in the virtualenv. However, it seems to work installing it normally. "Saving segmented videos to library" creates a 1.5gb file called video_collection in the --save_path. video_collection is found in the video_library.py. I think it's supposed to write a bunch of smaller files instead of 1 giant binary file.

**Comment by nyavramov** [comment]
I believe the reason that file is so big is that it contains a collection of uncompressed frames. Typically, you'd have some sort of compression in your input video that helps minimize the file size. 

Honestly, the save feature was not designed to be efficient and was more for my own testing & experimentation purposes.

I think you're probably better off importing the module and using it for whatever purposes you see fit. I.e.

```python
from fast_scene_detection.scene_extractor import SceneExtractor
from fast_scene_detection.video_library import VideoLibrary

video_library = VideoLibrary(video_list=[])
extractor = SceneExtractor(video_source='path/to/video.mp4', 
                           step_size_constant=0.00429584,
                           video_library=video_library)
extractor.process_scenes()
video = video_library.video_list[0]
video.get_scenes(n=40)

for extracted_scene in video.sorted_scenes:
    # Do something with the extracted scene. See the Scene class for
    # more details in scene.py
```

I hope that helps.

**Comment by DooDip** [comment]
Awesome! Thanks that helps.
